### ISSUE TITLE
Boolean filtering on related fields

### ISSUE THREAD

**Issue by mattwedge** [carltongibson/django-filter#1330] opened 2021-02-22 22:38 UTC
Not sure whether this is a bug or not but an issue I had recently:

Suppose we have a PetShop model with `animals` as the related name for the Animals in the pet shop. If we want to filter for just pet shops that have an animal with a tail we could do this:

`has_animal_with_tail = filters.BooleanFilter(field_name='animals__has_tail', distinct=True)`

Which works as expected in the positive case (when we filter for it being `True`), however when we filter for it being `False`, rather than returning the shops that don't have any animals with tails it gives us the shops that have some animal without a tail.

Similarly in the opposite case if we have a filter for shops that don't have any animals with tails:

`has_no_animal_with_tail = filters.BooleanFilter(field_name='animals__has_tail', distinct=True, exclude=True)`

This works fine in the positive case but when set to `False`, rather than giving shops that have some animal with a tail it gives shops that have only animals with tails.

In a way this is expected behaviour, but in another it is quite counterintuitive that the filtered sets when performing a boolean query are not one another's complements.

What would be a recommended workaround to this? Currently I just have both of the filters above and only use the positive case in either of them.

**Comment by dvf** [comment] 2021-03-06 01:30
Any updates here?

**Comment by carltongibson** [comment] 2021-03-06 04:30
This just looks like expected behaviour. Closing on that basis. 

You need to think about the generated SQL. 

Aside: The issue report is asking a lot of a reader. _"Please spend a lot of time thinking about this"_ — You need to expand it to **pinpoint an exact issue** if you really want people to be able to help.

**Closed by carltongibson** 2021-03-06 04:30 UTC
