### ISSUE TITLE
Question: Is it possible to at fields that are not on the model?

### ISSUE THREAD

**Issue by beruic** [carltongibson/django-filter#657] opened 2017-03-06 15:12 UTC
The reason for this question is that we have a model where fields available for this model (using another model for the definition) are dynamically added by the users. I would like to try to construct a class based on your work, that adds fields to the form based on the fields created by our users, and of course also add custom code to build the queryset.

**Comment by rpkilby** [comment] 2017-03-06 16:49
Hi @beruic - this is a question better suited for stackoverflow. 

----

That said, django-filter is an abstraction of the queryset API. If you can build a suitable query using the ORM, you can most likely represent the query using django-filter.

**Comment by carltongibson** [comment] 2017-03-06 20:39
@beruic, as said by @rpkilby. 

(I'm going to close this: it's not really an issue.)

If you can get to something a little more concrete then it's something that I'd be happy to think about on the mailing list. Current status is: _sounds cool but wondering about the cödz_ 🙂 

In general you can add fields to models, forms, and—why not?—filtersets dynamically. The issue is always the bookkeeping. It'd be interesting to see what you come up with (or where you get stuck)

**Closed by carltongibson** 2017-03-06 20:39 UTC
