### ISSUE TITLE
Update from 1.0.2 to 1.0.3 breaks

### ISSUE THREAD

**Issue by brianmay** [carltongibson/django-filter#720] opened 2017-05-17 22:04 UTC
Hello,

This update with from 1.0.2 to 1.0.3 - seems to have broken something. My tests fail with the following stack trace:

```
  File "/home/travis/build/Karaage-Cluster/karaage/karaage/plugins/kgsoftware/views.py", line 107, in software_list
    table = SoftwareTable(q_filter.qs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django_filters/filterset.py", line 200, in qs
    if not self.form.is_valid():
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django_filters/filterset.py", line 225, in form
    for name, filter_ in six.iteritems(self.filters)])
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django_filters/filters.py", line 158, in field
    label=self.label, widget=self.widget,
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django_filters/filters.py", line 114, in fget
    model, self.name, self.lookup_expr, self.exclude
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django_filters/utils.py", line 221, in label_for_filter
    name = verbose_field_name(model, field_name)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django_filters/utils.py", line 177, in verbose_field_name
    names.append(part.related_name.replace('_', ' '))
AttributeError: 'NoneType' object has no attribute 'replace'

```

I haven't had time yet to study this in detail, but as it is deep down inside ``django_filters`` code think I should report here.

Regards

**Comment by carltongibson** [comment] 2017-05-18 05:17
Thanks. Duplicate of #716

**Closed** 2017-05-18 11:47 UTC
