### ISSUE TITLE
Add support for optimized join paths in FilterSet

### ISSUE THREAD

**Issue by saichander17** [carltongibson/django-filter#1693] opened 2024-11-02 11:20 UTC
Currently when using multiple filter methods in a FilterSet that share common join paths, Django generates duplicate joins in the final query. This leads to less efficient queries and potential performance issues.

Example:
```python
class MyFilterSet(FilterSet):
    def status_filter(self, queryset, name, value):
        return queryset.filter(items__details__status=True)
        
    def category_filter(self, queryset, name, value):
        return queryset.filter(items__details__categories__id__in=[1,2])
```
When both filters are applied, the generated query contains duplicate joins:
```
SELECT DISTINCT ... FROM "parent" 
INNER JOIN "items" ON ("parent"."id" = "items"."parent_id") 
INNER JOIN "details" ON ("items"."id" = "details"."item_id") 
INNER JOIN "items" T4 ON ("parent"."id" = T4."parent_id") 
INNER JOIN "details" T5 ON (T4."id" = T5."item_id") 
WHERE ("details"."status" = true AND "categories"."id" IN (1, 2))
```

Maybe, Is it possible to create a new thing similar to filterset which has a behaviour where each filters returns Q() and the filter_queryset method collects all Q() and applies it to the queryset!

If there's already been any discussion on this or something similar which shows how to handle such scenarios, please do point me towards it. 

Currently, I'm thinking of creating a class inherited from filterset and modifying the init and filter_queryset methods to achieve this result.

**Comment by saichander17** [comment] 2024-11-21 05:46
Hi, 
Can someone please help here?

**Comment by carltongibson** [comment] 2024-11-21 06:34
You need to be creating a (multi-)filter that takes the (e.g. two) parameters and applies them in a single step.

See https://docs.djangoproject.com/en/5.1/topics/db/queries/#spanning-multi-valued-relationships

**Comment by carltongibson** [comment] 2024-11-21 06:51
There's an example for this pattern you can see here: https://gitlab.com/-/snippets/2237049

**Comment by carltongibson** [comment] 2024-11-21 06:55
Duplicate of  #1020.

**Closed by carltongibson** 2024-11-21 06:55 UTC
