### ISSUE TITLE
(2.0) FilterView always returning empty QuerySet for unbound FilterSet. 

### ISSUE THREAD

**Issue by vincentwhales** [carltongibson/django-filter#930] opened 2018-06-29 07:04 UTC
I have the a view, `AccountList`, which is trying to render a django_table2 table. The view's source code:

    class AccountList(SingleTableMixin, FilterView):
        model = Account
        table_class = AccountTable
        template_name = 'accounts/account_list.html'
        context_table_name = 'object_list'
        ordering = ['vps']
    
        filterset_class = AccountFilter

This view is currently using this filterset (from django_filters): 

    import django_filters
    from accounts.models import Account

    class AccountFilter(django_filters.FilterSet):
        class Meta:
            model = Account
            fields = ['is_suspended', 'is_abandoned']
    
        is_suspended = django_filters.BooleanFilter(name='is_suspended', initial='False')
        is_abandoned = django_filters.BooleanFilter(name='is_abandoned', initial='False')
    
        def __init__(self, data=None, *args, **kwargs):
            # if filterset is bound, use initial values as defaults
            if data is not None:
                # get a mutable copy of the QueryDict
                data = data.copy()
    
                for name, f in self.base_filters.items():
                    initial = f.extra.get('initial')
    
                    # filter param is either missing or empty, use initial as default
                    if not data.get(name) and initial:
                        data[name] = initial
    
            super().__init__(data, *args, **kwargs)

Using this template:

    {% if filter %}
        <form action="" method="get" class="form form-inline">
            {{ filter.form.as_p }}
            <input type="submit" />
        </form>
    {% endif %}
    
    {% render_table object_list %}
    
    {% endblock %}

This is my from my urls.py

    path('', login_required(AccountList.as_view())),

When I visit my page, `127.0.0.1:8000`, I see that the filters are not set:
[![enter image description here][1]][1]

But then if i do `127.0.0.1:8000?page=1`, I see the filters are initialized properly:

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/nGmAz.png
  [2]: https://i.stack.imgur.com/PDXBB.png

## What is causing my filters to not have default value when I don't have page=1 appended to my url?

**Comment by rpkilby** [comment] 2018-06-29 15:19
Try using an actual `False` boolean value instead of the string value `'False'`.

**Comment by vincentwhales** [comment] 2018-06-29 19:51
So when I tried the following:

    is_suspended = django_filters.BooleanFilter(name='is_suspended', initial=False)
    is_abandoned = django_filters.BooleanFilter(name='is_abandoned', initial=False)

This is how the filters are rendered on `127.0.0.1:8000/`

![image](https://user-images.githubusercontent.com/28204629/42111943-f3164c04-7b9a-11e8-9644-ad78f3bd71b3.png)

Even though the filter was rendered with the right values, the filter had no effect as I can still see accounts that are suspended or abandoned. 

Moreover, when I visit page 2 by pressing the `2` button at the bottom, I get to `http://127.0.0.1:8000/?page=2` with the filters resetting to `Unknown`.

![image](https://user-images.githubusercontent.com/28204629/42111956-072e8a12-7b9b-11e8-9a3d-15e8473ab287.png)

Do you see any reason why?

**Comment by rpkilby** [comment] 2018-06-29 20:06
Sorry - nothing obvious comes to mind. 

For the first issue, I'd recommend looking at the resulting SQL query. Make sure the suspended and abandoned filters are actually being applied.
For the second issue, I'd check the incoming data. It's possible that an invalid value is being provided to the `suspended` and `abandoned` filters when changing pages.

**Comment by vincentwhales** [comment] 2018-06-29 20:18
I inserted a few print statements and I found the following:

    def __init__(self, data=None, *args, **kwargs):
        if data is not None:        # 1
            data = data.copy()

            for name, f in self.base_filters.items():
                initial = f.extra.get('initial')   

                # filter param is either missing or empty, use initial as default
                if not data.get(name) and initial:
                    data[name] = initial

        super(BaseFilterSet, self).__init__(data, *args, **kwargs)

So it seems that `data` is `None`. Will you happen to know why my class based view is not passing `data` into `AccountFilter`?

**Comment by rpkilby** [comment] 2018-06-29 20:22
Hm. The `data` argument should always be provided by `FilterView`. 

https://github.com/carltongibson/django-filter/blob/b1f1c6592ef64a2172ec39040607a9c0b0714140/django_filters/views.py#L39-L46

Is `data` empty for both the first and second pages?

**Comment by moorchegue** [comment] 2018-07-28 04:19
Same problem here after upgrade to 2.0. Either default page or empty filter should be present in the URL to get the results. Is this at least documented somewhere?

**Comment by carltongibson** [comment] 2018-07-28 12:39
Still need more info to be able to reproduce...

**Comment by carltongibson** [comment] 2018-07-28 12:43
`page`? Isn't this to do with your pagination, rather than Django Filter?

**Comment by moorchegue** [comment] 2018-07-28 14:01
What info is needed exactly? Upgrading to 2.0 leads to the described behavior. Downgrading to 1.1.0 gets everything back to normal. I tried simplifying the view and the filterset to as minimalistic as possible, so it seems like this should be fairly easy to reproduce.

**Comment by rpkilby** [comment] 2018-07-28 20:47
@moorchegue, a minimal example test case or test project that demonstrates the issue would be helpful.

**Comment by carltongibson** [comment] 2018-07-29 06:30
It also looks like the issue is with whatever is providing your pagination logic. Yes, there may be some incompatibility with the new version, but debugging issues in other packages is out of scope. You need to demonstrate a bug in Django Filter for there to be anything we can do here.

**Comment by lggwettmann** [comment] 2018-08-02 22:49
Same problem here, but it has nothing to do with the pagination as far as I can judge. data is None when the url is without get paramenters, and it is True/False when the url contains get parameters. Any idea on how to solve this?

**Comment by carltongibson** [comment] 2018-08-03 08:01
OK, so the problem here is with the `is_valid()` method introduced as part of #788. 

https://github.com/carltongibson/django-filter/blob/1dde11c70eedeac32f6de92c426deb289e1aebd8/django_filters/filterset.py#L202-L206

This automatically returns `False` when `data` is `None`. 

In the view we're then setting `object_list` to `qs.none()`. ]

Hence the observed behaviour. 

The [test for this](https://github.com/carltongibson/django-filter/blob/1dde11c70eedeac32f6de92c426deb289e1aebd8/tests/test_views.py#L28-L31) isn't failing because the template is using `filter.qs` rather than `object_list`. 

https://github.com/carltongibson/django-filter/blob/1dde11c70eedeac32f6de92c426deb289e1aebd8/tests/templates/tests/book_filter.html#L3-L5

The immediate work around is to set `strict = False` on your filterset. This has consequence that actual invalid filter parameters will lead to partial filtering rather than showing empty results, but it should be workable for the now. (Better is to override the view `get` logic of course...) 

We'll have a think and improve the handling for the unbound case.

**Comment by rpkilby** [comment] 2018-08-03 17:07
Hm. The primary deficiency here is the disparity between the View's `object_list` and the FilterSet's `.qs`. Moving the strict behavior back to the `FilterSet.qs` would fix that. 

Additionally, there  is no strict/non-strict handling for the DRF backend.

**Comment by rpkilby** [comment] 2018-08-03 17:08
I'll WIP this up.

**Comment by jieter** [comment] 2018-09-04 07:34
@rpkilby Is there any progress on this issue?

**Comment by rpkilby** [comment] 2018-09-04 16:00
Yep - started the PR but had to put my open source work on hold. I should be able to pick up where I left off fairly soon.

**Comment by drvid** [comment] 2018-09-24 20:39
> The immediate work around is to set `strict = False` on your filterset. This has consequence that actual invalid filter parameters will lead to partial filtering rather than showing empty results, but it should be workable for the now. (Better is to override the view `get` logic of course...)

For what it's worth setting `strict = False` in my FilterSets did not solve this issue, because my templates are checking for existence of, and iterating over `object_list`.

The fix which worked for me was updating `object_list` in the templates to `filter.qs` which isn't too horrible... But I would still call it a regression.

**Comment by dyve** [comment] 2018-10-02 08:10
Note that the workaround should be to set `strict = False` on your `FilterMixin` descendant (probably the `View`.

**Comment by ekeydar** [comment] 2018-11-17 20:14
Can't you just change the condition to return the qs in case of unbounded form?

e.g.

```
-        if self.filterset.is_valid() or not self.get_strict():
+        if not self.filterset.is_bound or self.filterset.is_valid() or not self.get_strict():
```

**Closed** 2019-01-20 12:11 UTC
Labels: Bug
