### ISSUE TITLE
Tests fail with djangomaster

### ISSUE THREAD

**Issue by cdman** [carltongibson/django-filter#521] opened 2016-10-14 13:10 UTC
This is a result of https://github.com/tomchristie/django-rest-framework/issues/4574:

It seems that currently django-filter fails with Django master (using both Python 2.7 and 3.5). Trace:

```
FAIL: test_get_filtered_detail_view (tests.rest_framework.test_backends.IntegrationTestDetailFiltering)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gpanther/greypanther/django-filter/tests/rest_framework/test_backends.py", line 362, in test_get_filtered_detail_view
    self.assertEqual(response.data, data)
AssertionError: {'id'[26 chars]al': '0.25', 'date': '2012-10-08', 'basefilterableitem_ptr': 1} != {'id'[26 chars]al': '0.25', 'date': '2012-10-08'}

======================================================================
FAIL: test_filter_with_queryset (tests.rest_framework.test_backends.IntegrationTestFiltering)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gpanther/greypanther/django-filter/tests/rest_framework/test_backends.py", line 191, in test_filter_with_queryset
    self.assertEqual(response.data, expected_data)
AssertionError: [OrderedDict([('id', 3), ('text', 'ccc'), [72 chars]3)])] != [{'id': 3, 'text': 'ccc', 'decimal': '2.25[20 chars]04'}]

======================================================================
FAIL: test_get_filtered_class_root_view (tests.rest_framework.test_backends.IntegrationTestFiltering)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gpanther/greypanther/django-filter/tests/rest_framework/test_backends.py", line 214, in test_get_filtered_class_root_view
    self.assertEqual(response.data, self.data)
AssertionError: [OrderedDict([('id', 1), ('text', 'aaa'), [1145 chars]0)])] != [{'id': 1, 'text': 'aaa', 'decimal': '0.25[624 chars]20'}]

======================================================================
FAIL: test_get_filtered_fields_root_view (tests.rest_framework.test_backends.IntegrationTestFiltering)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gpanther/greypanther/django-filter/tests/rest_framework/test_backends.py", line 161, in test_get_filtered_fields_root_view
    self.assertEqual(response.data, self.data)
AssertionError: [OrderedDict([('id', 1), ('text', 'aaa'), [1145 chars]0)])] != [{'id': 1, 'text': 'aaa', 'decimal': '0.25[624 chars]20'}]

----------------------------------------------------------------------
Ran 382 tests in 0.756s

FAILED (failures=4, skipped=9, expected failures=3)
Destroying test database for alias 'default'...
```

**Comment by carltongibson** [comment] 2016-11-02 21:35
It's looking like this is an issue with DRF, Model Inheritance and `__all__` on Django master https://github.com/tomchristie/django-rest-framework/pull/4648

Will keep this open just to track for now.

**Comment by rpkilby** [comment] 2016-11-02 21:58
Oddly enough, I cannot reproduce this locally.

**Comment by carltongibson** [comment] 2016-11-03 08:18
In fact I'm pretty sure this is DRF's issue. I'll close it here. (We can always "Reopen")

**Closed by carltongibson** 2016-11-03 08:18 UTC
