### ISSUE TITLE
Behavior of `in` filter has changed

### ISSUE THREAD

**Issue by rtindru** [carltongibson/django-filter#684] opened 2017-04-12 07:07 UTC
We were using django-filter 0.13.0 where the URL filter such as `filed_name__in=` returns None which makes sense since the list is empty. After updating to django-filter 1.0.1 the same filter `fied_name__in=` returns ALL the elements.
For context, we use queries of the kind `user_id__in=1,2,3&` in the URL. When the list is empty, this query becomes `user_id__in=&` which evaluates to None of the users in the filter page for v 0.13.0. The same query now returns ALL users in v1.0.1

**Comment by carltongibson** [comment] 2017-04-12 18:50
This looks like expected behaviour to me. When the value is not provided no filtering occurs.

**Comment by rpkilby** [comment] 2017-04-12 18:51
Yep - this was fixed by #455 for the 0.14 release. In short, the old behavior is incorrect. Quoting myself from the original issue:

> Filtering on `param=` is usually skipped via empty value checking. The CSV widget is incorrectly parsing blank values as `['']`, which then bypasses the empty check on the filter and results in filtering against the empty value.

**Closed** 2017-04-12 18:51 UTC

**Comment by rtindru** [comment] 2017-04-13 04:42
Makes sense. Thanks @carltongibson @rpkilby.
