### ISSUE TITLE
Creating test database for alias 'default'...

### ISSUE THREAD

**Issue by lbazan** [carltongibson/django-filter#1069] opened 2019-04-11 19:12 UTC
+ /usr/bin/python3 runtests.py
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.......sssssss..................................................................................................s..x...F....ss..x..x..................................................................................................................................................................................................................................s....................sss.........................................................................................................
======================================================================
FAIL: test_filtering (tests.test_filtering.IsoDateTimeFromToRangeFilterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/django-filter-2.1.0/tests/test_filtering.py", line 1005, in test_filtering
    self.assertEqual(len(results.qs), 2)
AssertionError: 1 != 2

----------------------------------------------------------------------
Ran 487 tests in 0.839s

FAILED (failures=1, skipped=14, expected failures=3)
Destroying test database for alias 'default'...

**Comment by rpkilby** [comment] 2019-04-11 21:35
This is a duplicate of #1050

**Closed** 2020-03-12 03:44 UTC
