### ISSUE TITLE
Django 1.11 Compatibility

### ISSUE THREAD

**Issue by niknokseyer** [carltongibson/django-filter#712] opened 2017-05-12 20:44 UTC
I upgrade to Django 1.11 but I think there's some compatibility issues for the django-filter, I'm getting this error when I try to run the server:

`
ImportError: Could not import 'django_filters.rest_framework.DjangoFilterBackend' for API setting 'DEFAULT_FILTER_BACKENDS'. ImportError: cannot import name 'flatatt'.
`

**Comment by carltongibson** [comment] 2017-05-12 21:05
Version 1.0.2 added Django 1.11 compatibility, and we're testing against that in Travis

E.g. https://travis-ci.org/carltongibson/django-filter/jobs/227705729#L218

Can you check your versions?

**Comment by mheppner** [comment] 2017-05-13 18:49
I might need to open a new issue for this, but I'm having a problem after upgrading to Django 1.11 (with `django-filter==1.0.2`, `djangorestframework==3.6.3`, `django-crispy-forms==1.6.1`). I get a `Programming Error: can't use a named cursor outside of transactions` whenever an API view set has a `filter_fields` set. The traceback is happening on line 3, `filter.form.as_p` (similar issue when I turn crispy forms back on):

```
<h2>{% trans "Field filters" %}</h2>
<form class="form" action="" method="get">
    {{ filter.form.as_p }}
    <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
</form>
```

Do you want a new issue for this?

**Comment by carltongibson** [comment] 2017-05-14 07:28
> Do you want a new issue for this?

Yes please. If you can isolate the failure in a test case that would be awesome!

**Comment by mheppner** [comment] 2017-05-14 21:54
Ok it's #713. As for the original issue reported here, it's a duplicate of #673, which has already been fixed.

**Closed** 2017-05-16 19:00 UTC
