### ISSUE TITLE
django-filter-22.1 has a bug in filter

### ISSUE THREAD

**Issue by automationroad** [carltongibson/django-filter#1541] opened 2022-11-15 07:35 UTC
when I use django-filter-22.1 to filter something in views, it's not worke. it's look like this.
![image](https://user-images.githubusercontent.com/26619973/201856408-8977f0f4-805e-4aa5-acee-32ace02bb280.png)
I try to uninstall django-filter-22.1 and installed django-filter==21.1. It' well done.
![image](https://user-images.githubusercontent.com/26619973/201857196-ee85c7ea-0012-4d1b-81c6-fa84cf65b679.png)

**Comment by carltongibson** [comment] 2022-11-15 09:32
Likely duplicate of #1527.

Run with `python -Wall` and fix the warnings before updating.

**Closed by carltongibson** 2022-11-15 09:32 UTC
