### ISSUE TITLE
`CSVWidget` does not handle attrs parameters

### ISSUE THREAD

**Issue by tdelion** [carltongibson/django-filter#1093] opened 2019-07-02 12:52 UTC
It seems to me that `CSVWidget` does not handle `attrs` parameters. 

I would use it to give CSS class to the rendered form.

Is it an issue ?

**Comment by brenramz** [comment] 2019-10-22 23:50
I found that too, I hope it can be solved.

**Comment by airguru** [comment] 2020-03-03 12:01
Actually, I noticed that it passes the `attrs` when there is only one value present. With multiple values it does not pass the `attrs`. The relevant code is this: https://github.com/carltongibson/django-filter/blob/400469f03f7ebac6e0a7d8cbe6a7706f71e14c96/django_filters/widgets.py#L208-L219

It seems to render both options with `attrs`, but somehow it doesn't work. Maybe someone more competent can help?

**Comment by carltongibson** [comment] 2020-03-03 12:25
So, first thing is a minimal reproduce case, so we can look at the behaviour in question.

**Comment by rpkilby** [comment] 2020-03-04 16:17
Figured it out - what's confusing here is the render method's signature and how it interacts with the widget's initialized `attrs` (e.g., `CSVWidget(attrs={'foo': 'bar'}`). 

https://github.com/carltongibson/django-filter/blob/400469f03f7ebac6e0a7d8cbe6a7706f71e14c96/django_filters/widgets.py#L204

The initialized `attrs` aren't actually passed to the `render` method via its `attrs` argument. Instead, the `render` method should get its attrs through a call to `get_context`. For rendering single/no values, `BaseCSVWidget` does this by calling its parent's render method. However, for multiple values, we've created a surrogate text input without copying the `CSVWidget`'s attrs. So, when we render the surrogate widget, those attrs simply aren't present.

The question is whether this is the correct behavior, and I think that it generally is. `BaseCSVWidget` might be combined with something like a date picker input, and it wouldn't necessarily make sense to apply attrs intended for a date picker to the surrogate. However, for `CSVWidget` which is already mixed with a text input, it arguably does make sense that its attrs would be applied.

Should be fixed by #1177.

**Closed** 2020-03-04 17:02 UTC
